# Generated by Django on 2025-08-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('final_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('fully_indexed', 'Fully Indexed'), ('partially_indexed', 'Partially Indexed'), ('failed', 'Failed')], max_length=20)),
                ('extracted_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_account', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_uploaded', models.IntegerField(default=0)),
                ('fully_indexed', models.IntegerField(default=0)),
                ('partially_indexed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('total_file_size', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
