# Generated by Django 5.2.4 on 2025-08-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_add_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('total_uploaded', models.IntegerField(default=0)),
                ('fully_indexed', models.IntegerField(default=0)),
                ('partially_indexed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('total_file_size', models.BigIntegerField(default=0)),
                ('first_upload', models.DateTimeField(blank=True, null=True)),
                ('last_upload', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_upload'],
            },
        ),
    ]
